version: '3.6'

services:
  backend:
    image: orkeystore/server:latest
    ports:
      - '3000:3000'
    volumes:
      - /tmp/jwk-db:/tmp/jwk-db
    environment:
      ADMIN_PASSWORD: 'password'
      PRIVATE_HOST: 'http://localhost:3000'

  frontend:
    depends_on:
      - backend
    image: orkeystore/ui:latest
    ports:
      - '4000:3000'
    environment:
      API_URL: 'http://localhost:3000'
      API_SSR: 'http://backend:3000'